// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        int32              `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Category  string             `json:"category"`
	Tags      []string           `json:"tags"`
	Createdat pgtype.Timestamptz `json:"createdat"`
	Updatedat pgtype.Timestamptz `json:"updatedat"`
}
