// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (title, content, category, tags, createdAt, updatedAt)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, title, content, category, tags, createdAt, updatedAt
`

type CreatePostParams struct {
	Title    string   `json:"title"`
	Content  string   `json:"content"`
	Category string   `json:"category"`
	Tags     []string `json:"tags"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.Tags,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const deletePostByID = `-- name: DeletePostByID :one
DELETE
FROM posts
WHERE id = $1
RETURNING id, title, content, category, tags, createdAt, updatedAt
`

func (q *Queries) DeletePostByID(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRow(ctx, deletePostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, title, content, category, tags, createdAt, updatedAt
FROM posts
WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
SELECT id, title, content, category, tags, createdAt, updatedAt
FROM posts
`

func (q *Queries) GetPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.Tags,
			&i.Createdat,
			&i.Updatedat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostByID = `-- name: UpdatePostByID :one
UPDATE posts
SET title = $1,
    content = $2,
    category = $3,
    tags = $4,
    updatedAt = NOW()
WHERE id = $5
RETURNING id, title, content, category, tags, createdAt, updatedAt
`

type UpdatePostByIDParams struct {
	Title    string   `json:"title"`
	Content  string   `json:"content"`
	Category string   `json:"category"`
	Tags     []string `json:"tags"`
	ID       int32    `json:"id"`
}

func (q *Queries) UpdatePostByID(ctx context.Context, arg UpdatePostByIDParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePostByID,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.Tags,
		arg.ID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
