// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	DeletePostByID(ctx context.Context, id int32) (Post, error)
	GetPostByID(ctx context.Context, id int32) (Post, error)
	GetPosts(ctx context.Context) ([]Post, error)
	UpdatePostByID(ctx context.Context, arg UpdatePostByIDParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
